# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  github_organization: <%= ENV["GITHUB_ORG"] %>
  github_token: <%= ENV["GITHUB_TOKEN"] %>
  github_client_id: <%= ENV["GITHUB_CLIENT_ID"] %>
  github_client_secret: <%= ENV["GITHUB_CLIENT_SECRET"] %>
  github_secret_token: "foo" # for webhooks
  secret_key_base: b4c31c1303f597d79cab52403690d12578eac854d8c177ee108e035faf8bfa7f9d8c737a44ec59f857f3044351cf2f5dd8b7ff61940b31efdd26185d061b8098
  slack_api_token: <%= ENV["SLACK_API_TOKEN"] %>
  public_pull_request_secret: "supersecret"
  chrome_extension_secret: "supersecret"

test:
  secret_key_base: 46ba9325144637199819c19ae265b71d04888193287d68bebf92b200864e934f6b3f9fb61b9966f62e29e95a533f78f22013f89982c06edae777c7cd1776be66
  github_secret_token: "foo" # for webhooks
  github_organization: "bar"
  public_pull_request_secret: "supersecret"
  chrome_extension_secret: "supersecret"

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  github_organization: <%= ENV["GITHUB_ORG"] %>
  github_token: <%= ENV["GITHUB_TOKEN"] %>
  github_client_id: <%= ENV["GITHUB_CLIENT_ID"] %>
  github_client_secret: <%= ENV["GITHUB_CLIENT_SECRET"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  slack_api_token: <%= ENV["SLACK_API_TOKEN"] %>
  github_secret_token: <%= ENV["GITHUB_SECRET_TOKEN"] %> # for webhooks
  public_pull_request_secret: <%= ENV["PUBLIC_PULL_REQUEST_SECRET"] %>
  chrome_extension_secret: <%= ENV["CHROME_EXTENSION_SECRET"] %>
